# Generated by Django 5.2.4 on 2025-07-19 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0002_initial'),
        ('refunds', '0001_initial'),
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='farmer',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'Farmer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment_to_refund',
            field=models.ForeignKey(blank=True, help_text='Link to the specific payment being refunded, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_attempts', to='payment.payment'),
        ),
        migrations.AddField(
            model_name='refund',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_for_schedule', to='schedules.schedule'),
        ),
    ]
