# Generated by Django 5.2.3 on 2025-07-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='notes',
        ),
    ]
