# Generated by Django 5.2.3 on 2025-06-27 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('village', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('village_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='village.village')),
            ],
        ),
    ]
