# Generated by Django 4.2.23 on 2025-06-20 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperativeadmin', '0002_village'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('village_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooperativeadmin.village')),
            ],
        ),
    ]
