# Generated by Django 5.2.3 on 2025-06-20 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('village', '0002_rename_village_name_village_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village.village')),
            ],
        ),
    ]
