# Generated by Django 4.2.23 on 2025-06-25 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperativeadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=26)),
                ('email', models.CharField(max_length=100)),
                ('village_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativeadmin.village')),
            ],
        ),
    ]
