# Generated by Django 5.2.3 on 2025-07-27 09:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Farmer', 'Farmer'), ('Extentionworker', 'Extentionworker'), ('Admin', 'Admin')], default='Farmer', max_length=20, verbose_name='User Type'),
        ),
    ]
