# Generated by Django 5.2.3 on 2025-07-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='createdat',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='points_deducted',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('MPESA', 'MPESA'), ('CASH', 'Cash'), ('BANK', 'Bank')], default='MPESA', max_length=20),
        ),
    ]
