# Generated by Django 5.2.3 on 2025-06-27 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extension', '0001_initial'),
        ('trainings', '0001_initial'),
        ('village', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('extensionworker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='extension.extensionworker')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.trainings')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village.village')),
            ],
        ),
    ]
