# Generated by Django 5.2.3 on 2025-06-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedules',
            name='topic',
        ),
    ]
