# Generated by Django 5.2.4 on 2025-07-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_trainings'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='trainings',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
