# Generated by Django 5.2.3 on 2025-06-22 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('farmer', '0001_initial'),
        ('schedules', '0001_initial'),
        ('village', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.schedules'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='village.village'),
        ),
    ]
