# Generated by Django 5.2.3 on 2025-07-27 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='farmer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'Farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='rewards_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='reward',
            unique_together={('farmer', 'attendance')},
        ),
    ]
