# Generated by Django 5.2.3 on 2025-06-25 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewards',
            name='status',
        ),
    ]
