# Generated by Django 5.2.3 on 2025-06-27 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmer', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('refund_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_code', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer')),
                ('training_schedule_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.schedules')),
            ],
        ),
    ]
