# Generated by Django 5.2.3 on 2025-07-22 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedules'},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='scheduled_time',
        ),
    ]
