# Generated by Django 5.2.3 on 2025-07-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_alter_schedule_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='location_details',
        ),
    ]
