# Generated by Django 5.2.3 on 2025-06-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(max_length=100)),
                ('longtitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
    ]
