# Generated by Django 5.2.3 on 2025-06-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='village',
            old_name='village_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='village',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='village',
            name='longtitude',
        ),
    ]
