# Generated by Django 5.2.4 on 2025-07-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0002_rename_longtitude_village_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='village',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='village',
            name='longitude',
        ),
        migrations.AddField(
            model_name='village',
            name='village_cell',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
